name: ci

on:
  push:
    branches:
      - 'master'
# Environment variables available to all jobs and steps in this workflow
env:
  IMAGE_TAG: ${GITHUB_SHA::7}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        run: echo ${{env.IMAGE_TAG}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push       
        uses: docker/build-push-action@v2       
        with:
          push: true
          tags: nmanthena/angular:latest
        
  
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
          
#       - name: Build and push Angular Image
#         id: nmanthena/angular:${{ github.sha }}
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/angular:${{ env.IMAGE_TAG }}
